apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.namePrefix }}{{ .Values.namePrefix }}-{{ end }}{{ .Chart.Name }}-nginx
  labels:
    app.kubernetes.io/name: {{ if .Values.namePrefix }}{{ .Values.namePrefix }}-{{ end }}{{ .Chart.Name }}-nginx
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ if .Values.namePrefix }}{{ .Values.namePrefix }}-{{ end }}{{ .Chart.Name }}-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
